name: main
"on":
  push:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
      - shared/frontend-a/**
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
            frontend-a:
              - shared/frontend-a/**
  frontend-a-build:
    name: frontend-a-build
    if: needs.changes.changes.outputs.frontend-a == 'true'
    needs:
      - changes
    uses: ./.github/workflows/reusable_build.yaml
  terraform-deploy-dev:
    name: terraform-deploy-dev
    if: needs.changes.changes.outputs.terraform == 'true'
    needs:
      - changes
    uses: ./.github/workflows/reusable-apply-iac.yaml
    permissions:
      id-token: write
      contents: read
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-test:
    name: terraform-deploy-test
    if: needs.changes.changes.outputs.terraform == 'true'
    needs:
      - terraform-deploy-dev
    uses: ./.github/workflows/reusable-apply-iac.yaml
    permissions:
      id-token: write
      contents: read
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-prod:
    name: terraform-deploy-prod
    if: needs.changes.changes.outputs.terraform == 'true'
    needs:
      - terraform-deploy-test
    uses: ./.github/workflows/reusable-apply-iac.yaml
    permissions:
      id-token: write
      contents: read
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  frontend-a-deploy-dev:
    name: frontend-a-deploy-dev
    if: needs.changes.changes.outputs.frontend-a == 'true'
    needs:
      - frontend-a-build
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      packages: write
    with:
      github-environment: dev
  frontend-a-deploy-test:
    name: frontend-a-deploy-test
    if: needs.changes.changes.outputs.frontend-a == 'true'
    needs:
      - frontend-a-deploy-dev
      - frontend-a-build
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      packages: write
    with:
      github-environment: test
  frontend-a-deploy-prod:
    name: frontend-a-deploy-prod
    if: needs.changes.changes.outputs.frontend-a == 'true'
    needs:
      - frontend-a-deploy-test
      - frontend-a-build
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      packages: write
    with:
      github-environment: prod
