name: main
"on":
  push:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
      - shared/frontend-a/**
      - shared/frontend-b/**
    branches:
      - main
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      terraform: ${{ steps.changes.outputs.terraform }}
      frontend-a: ${{ steps.changes.outputs.frontend-a }}
      frontend-b: ${{ steps.changes.outputs.frontend-b }}
    steps:
      - uses: actions/checkout@v4
      - id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
            frontend-a:
              - shared/frontend-a/**
            frontend-b:
              - shared/frontend-b/**
  terraform-deploy-dev:
    name: terraform-deploy-dev
    if: ${{needs.changes.outputs.terraform == 'true'}}
    needs:
      - changes
    uses: ./.github/workflows/reusable-apply-iac.yaml
    permissions:
      id-token: write
      contents: read
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  frontend-a-build:
    name: frontend-a-build
    if: ${{needs.changes.outputs.frontend-a == 'true'}}
    needs:
      - changes
    uses: ./.github/workflows/reusable_build.yaml
    permissions:
      contents: read
      packages: write
  terraform-deploy-test:
    name: terraform-deploy-test
    if: ${{needs.changes.outputs.terraform == 'true'}}
    needs:
      - terraform-deploy-dev
    uses: ./.github/workflows/reusable-apply-iac.yaml
    permissions:
      id-token: write
      contents: read
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  frontend-b-build:
    name: frontend-b-build
    if: ${{needs.changes.outputs.frontend-b == 'true'}}
    needs:
      - changes
    uses: ./.github/workflows/reusable_build.yaml
    permissions:
      contents: read
      packages: write
  terraform-deploy-prod:
    name: terraform-deploy-prod
    if: ${{needs.changes.outputs.terraform == 'true'}}
    needs:
      - terraform-deploy-test
    uses: ./.github/workflows/reusable-apply-iac.yaml
    permissions:
      id-token: write
      contents: read
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  frontend-a-deploy-dev:
    name: frontend-a-deploy-dev
    if: ${{needs.changes.outputs.frontend-a == 'true'}}
    needs:
      - frontend-a-build
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      github-environment: dev
  frontend-a-deploy-test:
    name: frontend-a-deploy-test
    if: ${{needs.changes.outputs.frontend-a == 'true'}}
    needs:
      - frontend-a-deploy-dev
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      github-environment: test
  frontend-a-deploy-prod:
    name: frontend-a-deploy-prod
    if: ${{needs.changes.outputs.frontend-a == 'true'}}
    needs:
      - frontend-a-deploy-test
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      github-environment: prod
  frontend-b-deploy-dev:
    name: frontend-b-deploy-dev
    if: ${{needs.changes.outputs.frontend-b == 'true'}}
    needs:
      - frontend-b-build
      - terraform-deploy-dev
      - frontend-a-deploy-dev
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      github-environment: dev
  frontend-b-deploy-test:
    name: frontend-b-deploy-test
    if: ${{needs.changes.outputs.frontend-b == 'true'}}
    needs:
      - frontend-b-deploy-dev
      - terraform-deploy-test
      - frontend-a-deploy-test
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      github-environment: test
  frontend-b-deploy-prod:
    name: frontend-b-deploy-prod
    if: ${{needs.changes.outputs.frontend-b == 'true'}}
    needs:
      - frontend-b-deploy-test
      - terraform-deploy-prod
      - frontend-a-deploy-prod
    uses: ./.github/workflows/reusable_deploy.yaml
    permissions:
      contents: read
      id-token: write
    with:
      github-environment: prod
