name: main
"on":
  push:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
      - frontend/**
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
            frontend:
              - frontend/**
  frontend-build:
    name: frontend-build
    if: needs.filter.changes.outputs.frontend == 'true'
    uses: ./build.yaml
    with:
      test: test
  terraform-deploy-dev:
    name: terraform-deploy-dev
    if: needs.filter.changes.outputs.terraform == 'true'
    needs:
      - filter
    uses: ./reusable-apply-iac.yaml
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-test:
    name: terraform-deploy-test
    if: needs.filter.changes.outputs.terraform == 'true'
    needs:
      - filter
      - terraform-deploy-dev
    uses: ./reusable-apply-iac.yaml
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-prod:
    name: terraform-deploy-prod
    if: needs.filter.changes.outputs.terraform == 'true'
    needs:
      - filter
      - terraform-deploy-test
    uses: ./reusable-apply-iac.yaml
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  frontend-deploy-dev:
    name: frontend-deploy-dev
    if: needs.filter.changes.outputs.frontend == 'true'
    needs:
      - filter
    uses: ./deploy.yaml
    with:
      github-environment: dev
      test: test
  frontend-deploy-test:
    name: frontend-deploy-test
    if: needs.filter.changes.outputs.frontend == 'true'
    needs:
      - filter
      - frontend-deploy-dev
      - frontend-build
    uses: ./deploy.yaml
    with:
      github-environment: test
      test: test
  frontend-deploy-prod:
    name: frontend-deploy-prod
    if: needs.filter.changes.outputs.frontend == 'true'
    needs:
      - filter
      - frontend-deploy-test
      - frontend-build
    uses: ./deploy.yaml
    with:
      github-environment: prod
      test: test
