name: manual-deploy
"on":
  workflow_dispatch:
    inputs:
      workflow:
        description: Workflow to apply
        required: true
        type: choice
        options:
          - terraform
          - frontend-a
      env:
        description: Workflow to apply
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
        default: dev
jobs:
  terraform-deploy-dev:
    if: ${{ github.event.inputs.workflow == 'terraform' && github.event.inputs.env == 'dev' }}
    name: terraform-deploy-dev
    uses: ./.github/workflows/reusable-apply-iac.yaml
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-test:
    if: ${{ github.event.inputs.workflow == 'terraform' && github.event.inputs.env == 'test' }}
    name: terraform-deploy-test
    uses: ./.github/workflows/reusable-apply-iac.yaml
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  terraform-deploy-prod:
    if: ${{ github.event.inputs.workflow == 'terraform' && github.event.inputs.env == 'prod' }}
    name: terraform-deploy-prod
    uses: ./.github/workflows/reusable-apply-iac.yaml
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
  frontend-a-deploy-dev:
    if: ${{ github.event.inputs.workflow == 'frontend-a' && github.event.inputs.env == 'dev' }}
    name: frontend-a-deploy-dev
    uses: ./deploy.yaml
    with:
      github-environment: dev
      test: test
  frontend-a-deploy-test:
    if: ${{ github.event.inputs.workflow == 'frontend-a' && github.event.inputs.env == 'test' }}
    name: frontend-a-deploy-test
    uses: ./deploy.yaml
    with:
      github-environment: test
      test: test
  frontend-a-deploy-prod:
    if: ${{ github.event.inputs.workflow == 'frontend-a' && github.event.inputs.env == 'prod' }}
    name: frontend-a-deploy-prod
    uses: ./deploy.yaml
    with:
      github-environment: prod
      test: test
