name: pull_request
"on":
  pull_request:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
  terraform-preview-dev:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: terraform-preview-dev
    uses: ./reusable-preview-iac.yaml
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
    needs:
      - filter
  terraform-preview-test:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: terraform-preview-test
    uses: ./reusable-preview-iac.yaml
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
    needs:
      - filter
      - dev
  terraform-preview-prod:
    if: needs.filter.changes.outputs.terraform == 'true'
    name: terraform-preview-prod
    uses: ./reusable-preview-iac.yaml
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
    needs:
      - filter
      - test
