name: pull_request
"on":
  pull_request:
    paths:
      - terraform/*.tf
      - terraform/*.hcl
      - terraform/*.tfvars
jobs:
  changes:
    name: changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - id: changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            terraform:
              - terraform/*.tf
              - terraform/*.hcl
              - terraform/*.tfvars
  terraform-preview-dev:
    if: ${{needs.changes.outputs.terraform == 'true'}}
    name: terraform-preview-dev
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-preview-iac.yaml
    with:
      github-environment: dev
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
    needs:
      - changes
  terraform-preview-test:
    if: ${{needs.changes.outputs.terraform == 'true'}}
    name: terraform-preview-test
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-preview-iac.yaml
    with:
      github-environment: test
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
    needs:
      - terraform-preview-dev
  terraform-preview-prod:
    if: ${{needs.changes.outputs.terraform == 'true'}}
    name: terraform-preview-prod
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-preview-iac.yaml
    with:
      github-environment: prod
      tf-workspace: default
      tf-varfile: ""
      tf-path: terraform
    needs:
      - terraform-preview-test
