name: reusable Apply Infrastructure
"on":
  workflow_call:
    inputs:
      github-environment:
        required: true
        type: string
      tf-workspace:
        required: false
        type: string
      tf-varfile:
        required: false
        type: string
      tf-path:
        required: false
        type: string
        default: terraform
jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ inputs.github-environment }}
    steps:
      - name: fake apply
        shell: bash
        run: |-
          echo input: terraform-workspace=${{ inputs.tf-workspace }}
          echo input: variable-file=${{ inputs.tf-varfile }}
          echo input: working-directory=${{ inputs.tf-path}}
          echo input: github-environment=${{ inputs.github-environment}}
permissions:
  id-token: write
  contents: read
